/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.configdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ConfigDslTextualUiModule extends AbstractConfigDslTextualUiModule {

	public ConfigDslTextualUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
