/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.configdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractConfigDslTextualScopeProvider extends DelegatingScopeProvider {
}
