/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl.ide;


/**
 * Use this class to register ide components.
 */
public class ConstraintDslTextualIdeModule extends AbstractConstraintDslTextualIdeModule {
}
