/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import zombie.incatch.constraintdsl.ConstraintDslTextualRuntimeModule;
import zombie.incatch.constraintdsl.ConstraintDslTextualStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ConstraintDslTextualIdeSetup extends ConstraintDslTextualStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ConstraintDslTextualRuntimeModule(), new ConstraintDslTextualIdeModule()));
	}
	
}
