/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.configdsl.ide;


/**
 * Use this class to register ide components.
 */
public class ConfigDslTextualIdeModule extends AbstractConfigDslTextualIdeModule {
}
