/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.configdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import zombie.incatch.configdsl.ConfigDslTextualRuntimeModule;
import zombie.incatch.configdsl.ConfigDslTextualStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ConfigDslTextualIdeSetup extends ConfigDslTextualStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ConfigDslTextualRuntimeModule(), new ConfigDslTextualIdeModule()));
	}
	
}
