/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.configdsl.ui.tests;

import com.google.inject.Injector;
import confgiDslTextual.ui.internal.ConfgiDslTextualActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ConfigDslTextualUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConfgiDslTextualActivator.getInstance().getInjector("zombie.incatch.configdsl.ConfigDslTextual");
	}

}
