/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.configdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import zombie.incatch.configdsl.parser.antlr.internal.InternalConfigDslTextualParser;
import zombie.incatch.configdsl.services.ConfigDslTextualGrammarAccess;

public class ConfigDslTextualParser extends AbstractAntlrParser {

	@Inject
	private ConfigDslTextualGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConfigDslTextualParser createParser(XtextTokenStream stream) {
		return new InternalConfigDslTextualParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Config";
	}

	public ConfigDslTextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConfigDslTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
