/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractConstraintDslTextualScopeProvider extends DelegatingScopeProvider {
}
