/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl.ui.tests;

import com.google.inject.Injector;
import constraintDslTextual.ui.internal.ConstraintDslTextualActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ConstraintDslTextualUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConstraintDslTextualActivator.getInstance().getInjector("zombie.incatch.constraintdsl.ConstraintDslTextual");
	}

}
