/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ConstraintDslTextualStandaloneSetup extends ConstraintDslTextualStandaloneSetupGenerated {

	public static void doSetup() {
		new ConstraintDslTextualStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
