/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConstraintDslTextualRuntimeModule extends AbstractConstraintDslTextualRuntimeModule {
}
