/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ConstraintDslTextualUiModule extends AbstractConstraintDslTextualUiModule {

	public ConstraintDslTextualUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
