/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ConstraintDslTextualProposalProvider extends AbstractConstraintDslTextualProposalProvider {
}
