/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import zombie.incatch.constraintdsl.parser.antlr.internal.InternalConstraintDslTextualParser;
import zombie.incatch.constraintdsl.services.ConstraintDslTextualGrammarAccess;

public class ConstraintDslTextualParser extends AbstractAntlrParser {

	@Inject
	private ConstraintDslTextualGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConstraintDslTextualParser createParser(XtextTokenStream stream) {
		return new InternalConstraintDslTextualParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ConstraintCollection";
	}

	public ConstraintDslTextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConstraintDslTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
