/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.constraintdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ConstraintDslTextualAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("zombie/incatch/constraintdsl/parser/antlr/internal/InternalConstraintDslTextual.tokens");
	}
}
