/*
 * generated by Xtext 2.27.0
 */
package zombie.incatch.configdsl.ui;

import com.google.inject.Injector;
import confgiDslTextual.ui.internal.ConfgiDslTextualActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConfigDslTextualExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ConfgiDslTextualActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ConfgiDslTextualActivator activator = ConfgiDslTextualActivator.getInstance();
		return activator != null ? activator.getInjector(ConfgiDslTextualActivator.ZOMBIE_INCATCH_CONFIGDSL_CONFIGDSLTEXTUAL) : null;
	}

}
